name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Ih8passwards!
          POSTGRES_DB: FinalProject
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Install PostgreSQL client
      run: sudo apt-get install postgresql-client

    - name: Load database schema
      run: |
        psql -h localhost -U postgres -d FinalProject -f data/schema_only_backup.sql
      env:
        PGPASSWORD: Ih8passwards!

    - name: Insert test data
      run: |
        psql -h localhost -U postgres -d FinalProject <<EOF
        INSERT INTO users (id, username, password, firstname, lastname)
        VALUES (1, 'testuser', 'testpass', 'Test', 'User');

        INSERT INTO plant_info (id, commonname, latinname, description)
        VALUES (2, 'Basil', 'Ocimum basilicum', 'A fragrant herb.');

        INSERT INTO plant_info (id, commonname, latinname, description)
        VALUES (1, 'Spider Plant', 'Chlorophytum comosum', 'A popular houseplant.');

        INSERT INTO care (id, lighting, watering, soil, temperature, humidity, pet_safe)
        VALUES (1, 'Indirect light', 'Weekly', 'Well-draining', '65-75F', 'Medium', true);

        INSERT INTO plants_owned (id, user_id, plant_id)
        VALUES (1, 1, 1);

        INSERT INTO watering_log (id, date, amountw, fertilizer, amountf, user_id, plant_id)
        VALUES (1, CURRENT_DATE, 250, false, 0, 1, 1);
        EOF
      env:
        PGPASSWORD: Ih8passwards!

    - name: Run unit & integration tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: Ih8passwards!
        PGDATABASE: FinalProject
      run: |
        python -m pytest tests/

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Create executable with PyInstaller
      run: |
        mkdir -p dist
        pyinstaller --onefile --windowed --add-data "images/*;images/" src/FinalProjectApplication.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: HousePlantNursery
        path: dist/FinalProjectApplication.exe